sudo: false
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        EXECUTE_COVERAGE=true
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpstan analyze -c phpstan.neon --level=7 src/
